#Sample configuration information

#For other configuration files, you can use absolute paths
#or relative to the path to the anylink binary

#data file
db_type = "sqlite3"
db_source = "./conf/anylink.db"
#certificate file
cert_file = "./conf/vpn_cert.pem"
cert_key = "./conf/vpn_cert.key"
files_path = "./conf/files"

#Log directory, default is empty and writes to standard output
#log_path = "./log"
log_level = "debug"

#System name
issuer = "XX公司VPN"
#Backend management users
admin_user = "admin"
#pass 123456
admin_pass = "$2a$10$UQ7C.EoPifDeJh6d8.31TeSPQU7hM/NOM2nixmBucJpAuXDQNqNke"
# Leave it blank to disable otp. After otp is enabled, the password is pass + 6-digit otp.
# Generate ./anylink tool -o
admin_otp = ""
jwt_secret = "abcdef.0123456789.abcdef"

#Tcp service listening address (any port)
server_addr = ":443"
#Turn on DTLS
server_dtls = false
#Udp listening address (any port)
server_dtls_addr = ":443"
#Background service listening address
admin_addr = ":8800"

#Maximum number of clients
max_client = 200
#Number of simultaneous online users for a single user
max_user_client = 3

#Virtual network type [tun macvtap]
link_mode = "tun"
#IP address pool assigned by the client
#The docker environment generally defaults to eth0. In other cases, fill in the information based on the actual network card information.
ipv4_master = "eth0"
ipv4_cidr = "192.168.90.0/24"
ipv4_gateway = "192.168.90.1"
ipv4_start = "192.168.90.100"
ipv4_end = "192.168.90.200"

#Whether to automatically add nat
iptables_nat = true


#The client displays detailed error information (be careful when opening the online environment)
display_error = true


