# Sample configuration

# Other configuration files, you can use absolute paths
# or relative to the path to the anylink binary

files_path = "./conf/files"

# Log directory, default is empty and writes to standard output
log_path = ""

# Log level [debug info warn error]
log_level = "debug"

# Database
db_type = "sqlite3"
db_source = "./conf/anylink.db"

# Certificate file and key. Use the same certificate as nginx
cert_file = "./conf/vpn_cert.pem"
cert_key = "./conf/vpn_cert.key"

# Client profile
profile = "./conf/profile.xml"

# Used to distinguish configurations of different servers
profile_name = "anylink"

# Enable pprof
pprof = true

# System name
issuer = "XX公司VPN"

# Admin user
admin_user = "admin"

# Default password is 123456
admin_pass = "$2a$10$UQ7C.EoPifDeJh6d8.31TeSPQU7hM/NOM2nixmBucJpAuXDQNqNke"

# Leave it blank to disable otp. After otp is enabled, the password is pass + 6-digit otp.
# Generate ./anylink tool -o
admin_otp = ""

# JWT secret
jwt_secret = "abcdef.0123456789.abcdef"

# TCP service listening address (any port)
server_addr = ":443"

# Enable DTLS
server_dtls = false

# UDP listening address (any port)
server_dtls_addr = ":443"

# Web UI listening address
admin_addr = ":8800"

# Enable tcp proxy protocol
proxy_protocol = false

# Virtual network type [tun macvtap tap]
link_mode = "tun"

# IP address pool assigned by the client
# The Docker environment generally defaults to eth0. In other cases, fill in the information based on the actual network card information.
ipv4_master = "eth0"
ipv4_cidr = "192.168.90.0/24"
ipv4_gateway = "192.168.90.1"
ipv4_start = "192.168.90.100"
ipv4_end = "192.168.90.200"

# Maximum number of clients
max_client=200
# The number of simultaneous online users for a single user
max_user_client = 3
# IP lease period (seconds)
ip_lease = 86400

# Default selected group
default_group = "one"

# Client failure detection time (seconds) dpd > keepalive
cstp_keepalive=3
cstp_dpd = 20
mobile_keepalive = 4
mobile_dpd = 60

# Set the Maximum transmission unit (MTU)
mtu = 1460

# Default search domain for client DNS (separated by spaces)
default_domain = "example.com"

# Idle link timeout (seconds) - disconnect the link after timeout, 0 turns off this function
idle_timeout = 0

# Session expiration time, used for disconnection and reconnection, 0 will never expire
session_timeout = 3600

# Auth_timeout = 0
audit_interval = 600

# Display SQL statements for debugging
show_sql = false

# Whether to automatically add NAT rule
iptables_nat=true

# Enable compression
compression = false

# How many bytes less than and equal to are not compressed
no_compress_limit = 256

# Client displays detailed error information (be careful to enable online environment)
display_error = false

# Exclude export IP routing (export IP is not encrypted for transmission)
exclude_export_ip = true
