#Sample configuration information

#Other configuration files,You can use absolute paths
#or relative to anylink path to binary file

#data file
db_type = "sqlite3"
db_source = "./conf/anylink.db"
#certificate file Just use the same certificate as nginx
cert_file = "./conf/vpn_cert.pem"
cert_key = "./conf/vpn_cert.key"
files_path = "./conf/files"
profile = "./conf/profile.xml"
#profile name(Configuration used to distinguish different servers)
#Client storage location
#Windows 10
#%ProgramData%Cisco\Cisco AnyConnect Secure Mobility Client\Profile
#Mac Os X
#/opt/cisco/anyconnect/profile
#Linux
#/opt/cisco/anyconnect/profile
profile_name = "anylink"
#Log directory,Default is empty and writes to standard output.
#log_path = "./log"
log_path = ""
log_level = "debug"
pprof = true

#System name
issuer = "XX company VPN"
#Backend management users
admin_user = "admin"
#pass 123456
admin_pass = "$2a$10$UQ7C.EoPifDeJh6d8.31TeSPQU7hM/NOM2nixmBucJpAuXDQNqNke"
# Leave blank to disable it otp, After enabling otp, the password is  pass + 6 bit otp
# generate ./anylink tool -o
admin_otp = ""
jwt_secret = "abcdef.0123456789.abcdef"


#TCP service listening address(any port)
server_addr = ":443"
#turn on DTLS
server_dtls = false
#UDP listening address(any port)
server_dtls_addr = ":443"
#Background service listening address
admin_addr = ":8800"
#enable tcp proxy protocol
proxy_protocol = false

#Virtual network type[tun macvtap tap]
link_mode = "tun"

#IP address pool assigned by the client
#Docker environment generally defaults eth0, in other cases fill in according to the actual network card information
ipv4_master = "eth0"
ipv4_cidr = "192.168.90.0/24"
ipv4_gateway = "192.168.90.1"
ipv4_start = "192.168.90.100"
ipv4_end = "192.168.90.200"

#Maximum number of clients
max_client = 200
#Number of simultaneous online users for a single user
max_user_client = 3
#IP lease period(Second)
ip_lease = 86400

#Default selected group
default_group = "one"

#Client failure detection time(Second) dpd > keepalive
cstp_keepalive = 3
cstp_dpd = 20
mobile_keepalive = 4
mobile_dpd = 60

# Modify according to actual situation
#cstp_keepalive = 20
#cstp_dpd = 30
#mobile_keepalive = 40
#mobile_dpd = 60

#Set maximum transmission unit
mtu = 1460

# Default search domain for client dns
default_domain = "example.com"
#default_domain = "example.com abc.example.com"

#Idle link timeout(Second)-Disconnect the link after timeout, 0 turns off this feature
idle_timeout = 0
#session expiration time, used for disconnection and reconnection, 0 will never expire
session_timeout = 3600
#auth_timeout = 0
audit_interval = 600

show_sql = false

#Whether to automatically add nat
iptables_nat = true

#Enable compression
compression = false
#How many bytes less than and equal to are not compressed
no_compress_limit = 256

#Client displays detailed error information (be careful to enable online environment)
display_error = false

#Exclude export ip routing (export ip is not encrypted for transmission)
exclude_export_ip = true
