services:
  anylink:
    image: bjdgyc/anylink:latest
    container_name: anylink
    privileged: true
    ports:
      - 443:443/tcp
      - 8800:8800/tcp
      - 443:443/udp
    environment:
      LINK_LOG_LEVEL: info
    command:
      - --conf=/app/conf/server.toml
    volumes:
      - ./conf:/app/conf
    restart: always
